services:

  regression:

    volumes:
      - ./:/usr/workspace

    build:
      context: .
      dockerfile: Dockerfile

    command: ["/bin/sh", "-c", "ls -la && cd tests && pytest --alluredir=allure-results"]

    working_dir: /usr/workspace

    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}